### ISSUE TITLE
First script: Compiling a C program

### ISSUE THREAD

**Issue by caidongting0823** [umm-csci-3412-fall-2022/command-line-lab-1-lab0_dongbo#1]
Refer to CSCI 3412, Fall 2022, Lab 0, Task 1
https://github.com/umm-csci-3412-fall-2022/command-line-lab-1-lab0_dongbo#first-script-compiling-a-c-program

**Comment by YuboMao** [comment]
this step is finished.

**Comment by caidongting0823** [comment]
We are still working on this Issue. This Issue will be reopened.

**Comment by caidongting0823** [comment]
This Issue has been finished and will be closed. : )
